// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notes

import (
	"github.com/ghostrepo00/go-dashboard-api/domain/model"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Wire(setting *model.AppSettings, dbClient *gorm.DB) *handler {
	notesRepository := ProvideNotesRepository(dbClient)
	notesService := ProvideNotesService(notesRepository)
	notesHandler := ProvideNotesHandler(setting, notesService)
	return notesHandler
}
