definitions:
  model.Notes:
    properties:
      content:
        type: string
      id:
        format: uuid
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /notes:
    get:
      consumes:
      - application/json
      description: Get all notes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Notes'
            type: array
      summary: Get all notes
      tags:
      - Notes
    post:
      consumes:
      - application/json
      description: Create notes
      parameters:
      - description: New Notes
        in: body
        name: notes
        required: true
        schema:
          $ref: '#/definitions/model.Notes'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Notes'
      summary: Create notes
      tags:
      - Notes
  /notes/{id}:
    delete:
      consumes:
      - application/json
      description: Delete notes
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete notes
      tags:
      - Notes
    get:
      consumes:
      - application/json
      description: Get notes by id
      parameters:
      - description: Id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Notes'
      summary: Get notes by id
      tags:
      - Notes
    patch:
      consumes:
      - application/json
      description: Update notes
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      - description: Existing Notes
        in: body
        name: notes
        required: true
        schema:
          $ref: '#/definitions/model.Notes'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Notes'
      summary: Update notes
      tags:
      - Notes
swagger: "2.0"
